# Prepping Data Challenge - Week 22

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data

In [2]:
loyalty_points_df = pd.read_excel('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_22_Loyalty_Points_Extended.xlsx', sheet_name='Loyalty Points')
store_data_df = pd.read_excel('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_22_Loyalty_Points_Extended.xlsx', sheet_name='Store Data')
customer_details_df = pd.read_excel('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_22_Loyalty_Points_Extended.xlsx', sheet_name='Customer Details')

In [3]:
loyalty_points_df.head()

,RecordID,Email Address,Loyalty Points,Store ID,DateTime_Out,Right_RecordID
0,1,Aarika.d@wikispaces.com,/__ 1.2 \LotaltyScore,6,01-Dec-2023,1
1,2,Abbey.m@tiny.cc,/__ 0.2 \LotaltyScore,6,30-Mar-2023,2
2,3,Abbi.p@chronoengine.com,/__ 4.8 \LotaltyScore,8,28-Mar-2023,3
3,4,Abby.l@desdev.cn,/__ 2.1 \LotaltyScore,2,10-Apr-2023,4
4,5,Abbye.h@t-online.de,/__ 0.4 \LotaltyScore,2,28-Oct-2023,5

In [4]:
store_data_df.head()

         City          Store  Store ID
0      London  Oxford Street         1
1      London        Wembley         2
2      London       Richmond         3
3      London      Stratford         4
4  Manchester       Trafford         5

In [5]:
customer_details_df.head()

  First Name   Last Name Postcode       address
0     Aarika     Densham      NaN      Suite 52
1      Abbey      Moorey      NaN    12th Floor
2       Abbi      Parvin      NaN  PO Box 62649
3       Abby    Leonardi     6513      Suite 73
4      Abbye  Hazlehurst      NaN     8th Floor

## Challenge

**Goal:** Find the top 5 customers for each store, that do have a post code

### Feature Cleaning

In [6]:
# Convert Datetime to Datetime
loyalty_points_df['DateTime_Out'] = pd.to_datetime(loyalty_points_df['DateTime_Out'])

# Extract Loyalty Points as numeric
loyalty_points_df['Loyalty Points'] = loyalty_points_df['Loyalty Points'].apply(lambda x: float(x.split(' ')[1]))

In [7]:
loyalty_points_df.head()

,RecordID,Email Address,Loyalty Points,Store ID,DateTime_Out,Right_RecordID
0,1,Aarika.d@wikispaces.com,1.2,6,2023-12-01,1
1,2,Abbey.m@tiny.cc,0.2,6,2023-03-30,2
2,3,Abbi.p@chronoengine.com,4.8,8,2023-03-28,3
3,4,Abby.l@desdev.cn,2.1,2,2023-04-10,4
4,5,Abbye.h@t-online.de,0.4,2,2023-10-28,5

In [8]:
loyalty_points_df.shape

(999, 6)

### Joining Tables

In [9]:
# Extract information from Email Address for Join
loyalty_points_df['First Name'] = loyalty_points_df['Email Address'].apply(lambda x: x.split('.')[0])
loyalty_points_df['Last Name Initial'] = loyalty_points_df['Email Address'].apply(lambda x: x.split('.')[1].split('@')[0].upper())

In [10]:
# Extract initial of First Name from Customer DF
customer_details_df['Last Name Initial'] = customer_details_df['Last Name'].apply(lambda x: x[0].upper())

In [11]:
# Join all 3 DataFrames
joined_df = loyalty_points_df.merge(customer_details_df, on=['First Name', 'Last Name Initial'])
joined_df = joined_df.merge(store_data_df, on='Store ID')

In [12]:
# Remove unnecessary Fields
joined_df = joined_df.drop(columns=['Last Name Initial', 'Right_RecordID'])

In [13]:
joined_df.head()

,RecordID,Email Address,Loyalty Points,Store ID,DateTime_Out,First Name,Last Name,Postcode,address,City,Store
0,1,Aarika.d@wikispaces.com,1.2,6,2023-12-01,Aarika,Densham,NaN,Suite 52,Manchester,Salford
1,2,Abbey.m@tiny.cc,0.2,6,2023-03-30,Abbey,Moorey,NaN,12th Floor,Manchester,Salford
2,3,Abbi.p@chronoengine.com,4.8,8,2023-03-28,Abbi,Parvin,NaN,PO Box 62649,Birmingham,Birmingham
3,4,Abby.l@desdev.cn,2.1,2,2023-04-10,Abby,Leonardi,6513,Suite 73,London,Wembley
4,5,Abbye.h@t-online.de,0.4,2,2023-10-28,Abbye,Hazlehurst,NaN,8th Floor,London,Wembley

In [14]:
joined_df.shape

(999, 11)

### Find the top customers with postcodes

In [15]:
# Filter out customers without post codes
joined_df = joined_df[joined_df['Postcode'].notna()]

In [16]:
joined_df['Loyalty Rank'] = joined_df.groupby(['City', 'Store'])['Loyalty Points'].rank(method='min', ascending=False)

In [17]:
top_5_customers_df = joined_df[joined_df['Loyalty Rank'] <= 5].sort_values(['City', 'Store', 'Loyalty Rank'])

In [18]:
top_5_customers_df

,RecordID,Email Address,Loyalty Points,Store ID,DateTime_Out,First Name,Last Name,Postcode,address,City,Store,Loyalty Rank
43,44,Andros.k@cafepress.com,9.8,8,2023-05-02,Andros,Kopfer,55590,PO Box 8729,Birmingham,Birmingham,1.0
523,524,Karalee.m@addtoany.com,9.8,8,2023-11-20,Karalee,Marcq,5449,PO Box 93919,Birmingham,Birmingham,1.0
745,746,Ofilia.a@newyorker.com,9.6,8,2023-11-06,Ofilia,Aizikovich,4212,Room 1698,Birmingham,Birmingham,3.0
32,33,Alphonso.p@yahoo.co.jp,9.4,8,2023-09-30,Alphonso,Portam,3313,Suite 38,Birmingham,Birmingham,4.0
53,54,Archibald.w@prweb.com,9.2,8,2023-08-26,Archibald,Watkins,446017,Suite 90,Birmingham,Birmingham,5.0
348,349,Forbes.a@csmonitor.com,9.8,10,2023-04-24,Forbes,Allsopp,5616,14th Floor,Leeds,Leeds,1.0
881,882,Staffard.r@techcrunch.com,9.8,10,2023-03-06,Staffard,Ronan,17130,PO Box 30482,Leeds,Leeds,1.0
773,774,Peggy.b@vimeo.com,9.7,10,2023-04-13,Peggy,Braisted,641730,12th Floor,Leeds,Leeds,3.0
993,994,Zara.m@unblog.fr,9.6,10,2023-08-28,Zara,Marten,169660,Apt 119,Leeds,Leeds,4.0
18,19,Aldo.b@washingtonpost.com,9.4,10,2023-04-09,Aldo,Beetham,8710,Suite 15,Leeds,Leeds,5.0
187,188,Corine.f@sciencedaily.com,10.0,1,2023-01-19,Corine,Fidgeon,78726,20th Floor,London,Oxford Street,1.0
311,312,Euphemia.m@ask.com,10.0,1,2023-09-19,Euphemia,Marris,63-816,PO Box 60334,London,Oxford Street,1.0
266,267,Eberhard.d@simplemachines.org,9.9,1,2023-08-26,Eberhard,Dunklee,P5E,Apt 1324,London,Oxford Street,3.0
563,564,Kylie.l@jiathis.com,9.9,1,2023-03-17,Kylie,Lilliman,99-200,Apt 156,London,Oxford Street,3.0
669,670,Meade.h@china.com.cn,9.6,1,2023-08-27,Meade,Hellier,1296,Room 554,London,Oxford Street,5.0
23,24,Alfonso.e@dedecms.com,10.0,3,2023-09-06,Alfonso,Edmed,8290,10th Floor,London,Richmond,1.0
305,306,Estrella.p@dropbox.com,9.5,3,2023-09-26,Estrella,Parks,250 91,Room 677,London,Richmond,2.0
549,550,Killy.b@wiley.com,9.5,3,2023-03-18,Killy,Bricksey,20005,Apt 1403,London,Richmond,2.0
593,594,Leyla.a@nps.gov,9.1,3,2023-10-07,Leyla,Andrus,692150,16th Floor,London,Richmond,4.0
543,544,Kennie.c@cam.ac.uk,8.9,3,2023-10-27,Kennie,Campling,704038,Room 1244,London,Richmond,5.0
625,626,Lyn.r@state.gov,10.0,4,2023-05-18,Lyn,Rickaert,6804,6th Floor,London,Stratford,1.0
388,389,Glenda.d@hao123.com,9.9,4,2023-11-28,Glenda,Dwyer,363704,PO Box 92191,London,Stratford,2.0
795,796,Rabbi.s@quantcast.com,9.9,4,2023-05-07,Rabbi,Sorrie,89600-000,Suite 11,London,Stratford,2.0
962,963,Wait.v@hao123.com,9.5,4,2023-07-25,Wait,Vlasin,789 01,18th Floor,London,Stratford,4.0
290,291,Emelita.r@dell.com,9.2,4,2023-10-20,Emelita,Rolse,19001,7th Floor,London,Stratford,5.0
979,980,Win.l@1688.com,9.2,4,2023-08-06,Win,Lindsay,63800-000,Room 1243,London,Stratford,5.0
265,266,Ebeneser.f@kickstarter.com,9.8,2,2023-12-15,Ebeneser,Fennick,184021,Apt 192,London,Wembley,1.0
829,830,Rourke.z@a8.net,9.6,2,2023-09-27,Rourke,Zoanetti,4274,Apt 1258,London,Wembley,2.0
141,142,Carma.r@cornell.edu,9.4,2,2023-10-10,Carma,Raddish,197730,Apt 832,London,Wembley,3.0
581,582,Leo.s@yahoo.co.jp,9.0,2,2023-11-02,Leo,Sigge,453380,Suite 91,London,Wembley,4.0
717,718,Nanny.c@mac.com,8.8,2,2023-05-21,Nanny,Churchouse,1040,20th Floor,London,Wembley,5.0
587,588,Lesli.c@feedburner.com,9.7,7,2023-11-19,Lesli,Chesher,621 75,PO Box 31036,Manchester,Chorlton,1.0
247,248,Dody.g@hubpages.com,9.6,7,2023-12-04,Dody,Guerre,64-320,PO Box 36383,Manchester,Chorlton,2.0
945,946,Uta.d@yale.edu,8.7,7,2023-10-24,Uta,Durden,94109 CEDEX,Apt 1017,Manchester,Chorlton,3.0
342,343,Filippo.m@arizona.edu,8.6,7,2023-06-28,Filippo,Muddiman,134 61,Apt 1957,Manchester,Chorlton,4.0
107,108,Blancha.s@patch.com,8.4,7,2023-10-18,Blancha,Snawdon,6013,Suite 73,Manchester,Chorlton,5.0
539,540,Kelly.e@stumbleupon.com,8.4,7,2023-06-06,Kelly,Emerton,446533,7th Floor,Manchester,Chorlton,5.0
7,8,Addie.r@reddit.com,9.8,6,2023-10-10,Addie,Rene,9024,Apt 1028,Manchester,Salford,1.0
895,896,Suzann.g@etsy.com,9.4,6,2023-11-23,Suzann,Grigolli,141 48,18th Floor,Manchester,Salford,2.0
174,175,Cobbie.k@cbsnews.com,9.3,6,2023-03-29,Cobbie,Kinglake,431045,Room 285,Manchester,Salford,3.0
191,192,Cory.k@taobao.com,9.3,6,2023-09-17,Cory,Kemwal,9706,PO Box 5244,Manchester,Salford,3.0
312,313,Evaleen.g@omniture.com,9.3,6,2023-12-27,Evaleen,Gemeau,392558,Suite 75,Manchester,Salford,3.0
590,591,Lesya.r@mtv.com,9.9,5,2023-03-27,Lesya,Rosander,055827,Apt 42,Manchester,Trafford,1.0
474,475,Jaye.c@va.gov,9.8,5,2023-10-07,Jaye,Claughton,54300,Room 324,Manchester,Trafford,2.0
663,664,Maurizia.b@ucoz.com,9.8,5,2023-01-15,Maurizia,Boyce,76310-000,PO Box 78234,Manchester,Trafford,2.0
631,632,Madeleine.e@statcounter.com,9.6,5,2023-03-29,Madeleine,Ellul,45032 CEDEX 1,Room 1080,Manchester,Trafford,4.0
448,449,Ingamar.s@themeforest.net,9.5,5,2023-11-11,Ingamar,Stanmer,18-200,PO Box 17904,Manchester,Trafford,5.0
617,618,Lotta.v@adobe.com,9.5,5,2023-06-03,Lotta,Vial,11-130,Room 360,Manchester,Trafford,5.0
422,423,Hayden.d@upenn.edu,9.9,9,2023-04-29,Hayden,Damerell,92864 CEDEX 9,Room 635,Nottingham,Nottingham,1.0
235,236,Derick.g@eventbrite.com,9.8,9,2023-01-13,Derick,Goodship,R3L,Room 1280,Nottingham,Nottingham,2.0
627,628,Lynn.b@craigslist.org,9.7,9,2023-08-23,Lynn,Bushby,6112,PO Box 21922,Nottingham,Nottingham,3.0
124,125,Brynna.l@de.vu,8.5,9,2023-01-22,Brynna,Lord,MD-6214,PO Box 45832,Nottingham,Nottingham,4.0
842,843,Sarge.b@hibu.com,8.5,9,2023-05-06,Sarge,Blackesland,1556,PO Box 70040,Nottingham,Nottingham,4.0

## Save Data

In [19]:
top_5_customers_df.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/outputs/22_top_5_customers.csv')