# Prepping Data Challenge - Week 13

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data

In [2]:
data_2020 = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_13_products_2020.csv')
data_2021 = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_13_products_2021.csv')
data_2022 = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_13_products_2022.csv')
data_2023 = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_13_products_2023.csv')
data_2024 = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_13_products_2024.csv')

In [3]:
data_2020.head()

  Sales Date                            Product  Price  Quantity Sold
0  20/1/2020             Egg-citing Citrus Soap   1.50             20
1  20/1/2020      Eggcellent Citrus Splash Soap   1.25             16
2  20/1/2020  Hot Cross Bun & Honey Almond Soap   2.00             21
3  20/1/2020       Spring Meadow Goat Milk Soap   3.75             28
4  21/1/2020  Chocolate Bunny Exfoliating Scrub  10.00             16

In [4]:
data_2021.head()

  Sales Date                            Product  Price  Quantity Sold
0  11/1/2021       Bunny Kisses Shea Butter Bar   6.00             36
1  11/1/2021  Chocolate Bunny Exfoliating Scrub  10.00             25
2  11/1/2021      Eggcellent Citrus Splash Soap   1.25              6
3  11/1/2021  Hot Cross Bun & Honey Almond Soap   2.00             33
4  11/1/2021          Sunshine Bunny Honey Soap   4.00             38

In [5]:
data_2022.head()

  Sales Date                            Product  Price  Quantity Sold
0  24/1/2022        Blossom Breeze Bath Fizzies   7.00             21
1  24/1/2022               Bunny Hop Bubble Bar   4.00             15
2  24/1/2022       Bunny Kisses Shea Butter Bar   6.00             38
3  24/1/2022  Chocolate Bunny Exfoliating Scrub  10.00             17
4  24/1/2022      Eggcellent Citrus Splash Soap   1.25              3

In [6]:
data_2023.head()

  Sales Date                             Product  Price  Quantity Sold
0  16/1/2023         Blossom Breeze Bath Fizzies    7.0              5
1  16/1/2023                Bunny Hop Bubble Bar    4.0             18
2  16/1/2023   Chocolate Bunny Exfoliating Scrub   10.0             23
3  16/1/2023  Cinnamon Spice Hot Cross Bun Scrub   11.0             38
4  16/1/2023               Honey Bunny Oaty Soap    3.0             19

In [7]:
data_2024.head()

  Sales Date                            Product  Price  Quantity Sold
0   8/1/2024        Blossom Breeze Bath Fizzies    7.0             25
1   8/1/2024         Bunny Trail Botanical Soap    5.0             24
2   8/1/2024   Chocolate Bunny Bliss Bath Bombs   15.0              5
3   8/1/2024  Chocolate Truffle Bunny Scrub Bar    6.0             24
4   8/1/2024     Easter Basket Bliss Bubble Bar    8.0             11

### Sales Date to datetime

In [8]:
dataframes = [data_2020, data_2021, data_2022, data_2023, data_2024]

In [9]:
for df in dataframes:
    df['Sales Date'] = pd.to_datetime(df['Sales Date'], format='%d/%m/%Y')

### Add an 'Easter Week' column

In [10]:
# Check if all DataFrames have the same number of weeks and check if each first sales date is a monday
for df in dataframes:
    print(df['Sales Date'].dt.isocalendar().week.nunique())

12
12
12
12
12

All DataFrames have the same number of weeks

#### Add an Easter Sale Week Number for each Year

In [11]:
for df in dataframes:
    df['Easter Sale Week Number'] = df['Sales Date'].dt.isocalendar().week - df['Sales Date'].dt.isocalendar().week.min() + 1

#### Add weekday name and number

In [12]:
for df in dataframes:
    df['Weekday'] = df['Sales Date'].dt.strftime('%a')      # Abbreviation of the weekday
    df['Weekday Order'] = df['Sales Date'].dt.weekday + 1   # Number for each weekday, starting at 1 = Monday

### Concatenate DataFrames

In [13]:
all_sales = pd.concat(dataframes).reset_index(drop=True)

In [14]:
all_sales.head()

,Sales Date,Product,Price,Quantity Sold,Easter Sale Week Number,Weekday,Weekday Order
0,2020-01-20,Egg-citing Citrus Soap,1.50,20,1,Mon,1
1,2020-01-20,Eggcellent Citrus Splash Soap,1.25,16,1,Mon,1
2,2020-01-20,Hot Cross Bun & Honey Almond Soap,2.00,21,1,Mon,1
3,2020-01-20,Spring Meadow Goat Milk Soap,3.75,28,1,Mon,1
4,2020-01-21,Chocolate Bunny Exfoliating Scrub,10.00,16,1,Tue,2

In [15]:
print(all_sales.shape)

(1752, 7)

### Calculate sum of Sales per Day and product

A simple multiplication of price times quantity

In [16]:
all_sales['Sales'] = all_sales['Price'] * all_sales['Quantity Sold']

In [17]:
all_sales

,Sales Date,Product,Price,Quantity Sold,Easter Sale Week Number,Weekday,Weekday Order,Sales
0,2020-01-20,Egg-citing Citrus Soap,1.50,20,1,Mon,1,30.0
1,2020-01-20,Eggcellent Citrus Splash Soap,1.25,16,1,Mon,1,20.0
2,2020-01-20,Hot Cross Bun & Honey Almond Soap,2.00,21,1,Mon,1,42.0
3,2020-01-20,Spring Meadow Goat Milk Soap,3.75,28,1,Mon,1,105.0
4,2020-01-21,Chocolate Bunny Exfoliating Scrub,10.00,16,1,Tue,2,160.0
...,...,...,...,...,...,...,...,...
1747,2024-03-25,Honey Bunny Oaty Soap,3.00,6,12,Mon,1,18.0
1748,2024-03-25,Hot Cross Bun Soap Bar,5.00,17,12,Mon,1,85.0
1749,2024-03-25,Lavender Fields Bunny Soap,2.50,8,12,Mon,1,20.0
1750,2024-03-25,Spring Garden Petal Soap,3.50,22,12,Mon,1,77.0
1751,2024-03-25,Spring Raindrop Handcrafted Soap,3.00,18,12,Mon,1,54.0

## Save Data

The challenge notebook also contains the year as a column (which is smart, if you want to do the operations after the join) I don't think this is necessary here.

In [18]:
all_sales.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/outputs/13_easter_sales.csv')