# Prepping Data Challenge 2024 - Week 01

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [3]:
import datetime

## Import Data Set

In [2]:
data = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/PD_2024_Wk_1_Input.csv')

In [29]:
data['Flight Details'].loc[4]

'2024-10-01//PA008//Perth-New York//Business Class//634.79999999999995'

In [6]:
prepared_data = data.copy()

## Tasks

### 1. Split the flight details field

Target variables:
- `Date`
- `Flight Number`
- `From`
- `To`
- `Class`
- `Price`

#### First idea: use apply method on strings in `Flight Details`

In [36]:
def split_flight_details(flight_details):
    # Split Data into list of variables
    list_of_variables = str(flight_details).split('//')
    
    # To be more prudent, we will assume missing values
    try:
        # Date
        date = np.datetime64(list_of_variables[0])
    except:
        date = np.nan

    try:
        # Flight Number
        flight_number = list_of_variables[1]
    except:
        flight_number = np.nan

    try:
        # From and To
        from_to = list_of_variables[2].split('-')
        from_ = from_to[0]
        to = from_to[1]

    except:
        from_ = np.nan
        to = np.nan

    try:
        # Class
        class_ = list_of_variables[3]

    except:
        class_ = np.nan

    try:
        # Price
        price = float(list_of_variables[4])
    except:
        price = np.nan

    return pd.Series({'Date' : date, 'Flight Number' : flight_number, 'From' : from_, 'To' : to, 'Class' : class_, 'Price' : price})

Make the columns

In [37]:
prepared_data[['Date', 'Flight Number', 'From', 'To', 'Class', 'Price']] = data['Flight Details'].apply(split_flight_details)

Drop the `Flight Details` column

In [40]:
prepared_data = prepared_data.drop(['Flight Details'], axis=1)

### Change Card holder field to Yes / No

In [45]:
prepared_data['Flow Card?'] = prepared_data['Flow Card?'].map({1 : 'Yes', 0 : 'No'})

### Split the data set into two, based on `Flow Card?` value

In [46]:
flow_card_holders = prepared_data[prepared_data['Flow Card?'] == 'Yes']
flow_card_haters = prepared_data[prepared_data['Flow Card?'] == 'No']

In [47]:
flow_card_holders

,Flow Card?,Bags Checked,Meal Type,Date,Flight Number,From,To,Class,Price
0,Yes,0,Egg Free,2024-07-22,PA010,Tokyo,New York,Economy,2380.0
2,Yes,1,Vegan,2024-04-20,PA002,New York,London,Economy,3490.0
3,Yes,1,Vegetarian,2024-01-23,PA010,Tokyo,New York,Premium Economy,825.0
6,Yes,3,Vegan,2024-06-05,PA006,Tokyo,London,First Class,618.0
8,Yes,1,Nut Free,2024-03-30,PA004,Perth,London,First Class,446.0
...,...,...,...,...,...,...,...,...,...
3764,Yes,2,Egg Free,2024-11-23,PA005,London,Tokyo,Economy,2070.0
3766,Yes,3,Nut Free,2024-11-04,PA003,London,Perth,First Class,210.0
3770,Yes,0,Dairy Free,2024-04-29,PA012,Tokyo,Perth,Economy,3490.0
3772,Yes,2,Vegetarian,2024-09-26,PA001,London,New York,First Class,207.0
3777,Yes,1,Nut Free,2024-01-06,PA004,Perth,London,First Class,236.0

In [48]:
flow_card_haters

,Flow Card?,Bags Checked,Meal Type,Date,Flight Number,From,To,Class,Price
1,No,2,Vegetarian,2024-09-28,PA008,Perth,New York,Economy,1855.0
4,No,0,Vegetarian,2024-10-01,PA008,Perth,New York,Business Class,634.8
5,No,3,Nut Free,2024-03-04,PA007,New York,Perth,Business Class,458.4
7,No,0,NaN,2024-02-25,PA010,Tokyo,New York,Premium Economy,1435.0
13,No,2,Vegan,2024-03-29,PA004,Perth,London,Economy,2730.0
...,...,...,...,...,...,...,...,...,...
3771,No,2,Vegetarian,2024-03-06,PA006,Tokyo,London,Premium Economy,940.0
3773,No,3,Nut Free,2024-05-05,PA009,New York,Tokyo,Economy,1360.0
3774,No,1,Dairy Free,2024-06-14,PA008,Perth,New York,First Class,245.0
3775,No,2,Egg Free,2024-01-16,PA010,Tokyo,New York,Economy,2410.0
3776,No,0,Nut Free,2024-08-16,PA005,London,Tokyo,Premium Economy,960.0

## Save the results for the upcoming challenges

In [49]:
flow_card_holders.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/flow_card_holders.csv', index=False)
flow_card_haters.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/flow_card_haters.csv', index=False)