# Prepping Data Challenge - Week 16
**Budget vs. Actuals**

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data

In [2]:
budget = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_16_Budget.csv')
actual = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_16_Actual.csv')

In [3]:
actual

              2022        Actual
0             Rent  1,000,000.00
1        Utilities    111,063.02
2         Security     90,000.00
3            Wages    270,000.00
4        Inventory  2,654,003.11
5   Transportation    214,814.87
6  TransactionFees     59,395.92
7      Advertising    306,899.96
8        Insurance     70,000.00

In [4]:
budget = budget.dropna()
budget

,2022,Budget,Notes
0,Rent,"1,000,000",Same as last year
1,Utilities,"120,000",Appx
2,Security,"90,000",Already paid
4,Wages,270K,ADJUSTED
6,Inventory,"2,300,000",More less
7,Transportation,"180,000",More less
8,Transaction Fees,"54,000","That was last year, probably higher this year"
9,Advertising,"300,000",Ask Mark about exact sum
11,Insurance,70K,Exactly 70K

## Challenges

### Budget Column formatting

In [5]:
budget['Budget'] = budget['Budget'].apply(lambda x: int(x.replace('K', '000').replace(',','')))

In [6]:
actual['Actual'] = actual['Actual'].apply(lambda x: float(x.replace(',', '')))

### Join datasets

In [7]:
comparison = budget.merge(actual, on='2022')

# Drop the 'Notes' column
comparison = comparison[['2022', 'Budget', 'Actual']]

# Change the column names
comparison.columns = ['Category', 'Forecasted Spending', 'Actual Spending']

# Calculate the difference
comparison['Difference'] = comparison['Actual Spending'] - comparison['Forecasted Spending']
comparison['Difference'] = comparison['Difference'].astype(int)

In [8]:
comparison

         Category  Forecasted Spending  Actual Spending  Difference
0            Rent              1000000       1000000.00           0
1       Utilities               120000        111063.02       -8936
2        Security                90000         90000.00           0
3           Wages               270000        270000.00           0
4       Inventory              2300000       2654003.11      354003
5  Transportation               180000        214814.87       34814
6     Advertising               300000        306899.96        6899
7       Insurance                70000         70000.00           0

## Save Data

In [9]:
comparison.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/outputs/16_budget_comparison.csv')