# Prepping Data Challenge - Week

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data

In [2]:
stock_per_store = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_14_Stock_per_Store.csv')
recalled_items = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/inputs/PD_2024_Wk_14_Recalled_Items.csv')

In [3]:
stock_per_store.head()

,City,Store,Store ID,Category,Product ID,Unit Price,Quantity
0,Birmingahm,Birmingham,8,Groceries,GR1711,35.01,32
1,London,Richmond,3,Groceries,GR5380,5.13,31
2,Manchester,Chorlton,7,Groceries,GR9966,39.92,20
3,London,Stratford,4,Groceries,GR1840,41.32,42
4,London,Stratford,4,Groceries,GR5052,31.65,44

In [4]:
recalled_items.head()

    Category Product ID  Unit Price
0  Groceries     GR1840       41.32
1  Groceries     GR2261       38.20
2  Groceries     GR7679       40.06
3  Groceries     GR0294       11.77
4  Groceries     GR1705       47.16

In [7]:
stock_per_store['Product ID'].nunique()

1241

In [8]:
recalled_items.shape

(58, 3)

## Challenges

### Locate which item is in which store

In [11]:
recalled_items['Recalled'] = True
stock_with_recall = stock_per_store.merge(recalled_items, on=['Category', 'Product ID', 'Unit Price'], how='left')

### Calculate how much money was lost

In [19]:
stock_with_recall['Loss'] = np.where(stock_with_recall['Recalled'] == True, stock_with_recall['Unit Price'] * stock_with_recall['Quantity'], np.nan)

### Money lost by category

In [30]:
loss_by_category = stock_with_recall.groupby('Category')['Loss'].sum().reset_index()
loss_by_category

      Category      Loss
0       Beauty   6900.75
1      Clothes   9661.04
2  Electronics   9051.49
3    Groceries  16288.19
4         Home  12293.51

In [31]:
loss_by_category.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/outputs/14_loss_by_category.csv')

### Loss by store

In [36]:
loss_by_store = stock_with_recall.groupby('Store')['Loss'].sum().reset_index()

In [38]:
loss_by_store['Priority'] = np.where(loss_by_store['Loss'] >= 5000, 'High Priority', 'Low Priority')

In [39]:
loss_by_store

           Store      Loss       Priority
0     Birmingham   4617.89   Low Priority
1       Chorlton   4387.12   Low Priority
2          Leeds  11765.35  High Priority
3     Nottingham   5642.64  High Priority
4  Oxford Street   6772.84  High Priority
5       Richmond   1187.85   Low Priority
6        Salford   4608.70   Low Priority
7      Stratford   4341.70   Low Priority
8       Trafford   6326.95  High Priority
9        Wembley   4543.94   Low Priority

In [40]:
loss_by_store.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/outputs/14_loss_by_store.csv')