# Prepping Data Challenge - Week 03

**Performance against targets**

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data

#### Output Data From Week 1

In [2]:
flow_card_haters = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/flow_card_haters.csv')
flow_card_holders = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/flow_card_holders.csv')

In [37]:
sales_data = pd.concat([flow_card_haters.copy(), flow_card_holders.copy()]).reset_index(drop=True)

#### New Quarterly Data

In [3]:
q1_data = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/PD_2024_Wk_3_Input_Q1.csv')
q2_data = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/PD_2024_Wk_3_Input_Q2.csv')
q3_data = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/PD_2024_Wk_3_Input_Q3.csv')
q4_data = pd.read_csv('D:01_Projekt_Portfolio/data_prepping_challenges/PD_2024_Wk_3_Input_Q4.csv')

In [12]:
target_data = pd.concat([q1_data.copy(), q2_data.copy(), q3_data.copy(), q4_data.copy()]).reset_index(drop=True)

## Challenges

### 1. Correct the classes of flights

In [38]:
sales_data['Class'] = sales_data['Class'].map({'Economy' : 'First Class', 'First Class' : 'Economy', 'Premium Economy' : 'Business Class', 'Business Class' : 'Premium Economy'})

### 2. Adjust the Flight classes to the first letter pattern

In [41]:
# Hard to read but elegant solution: Take the first letter of every word
sales_data['Class'] = sales_data['Class'].apply(lambda x: "".join([w[0] for w in x.split(' ')]))

In [42]:
sales_data

,Flow Card?,Bags Checked,Meal Type,Date,Flight Number,From,To,Class,Price
0,No,2,Vegetarian,2024-09-28,PA008,Perth,New York,FC,1855.0
1,No,0,Vegetarian,2024-10-01,PA008,Perth,New York,PE,634.8
2,No,3,Nut Free,2024-03-04,PA007,New York,Perth,PE,458.4
3,No,0,NaN,2024-02-25,PA010,Tokyo,New York,BC,1435.0
4,No,2,Vegan,2024-03-29,PA004,Perth,London,FC,2730.0
...,...,...,...,...,...,...,...,...,...
3773,Yes,2,Egg Free,2024-11-23,PA005,London,Tokyo,FC,2070.0
3774,Yes,3,Nut Free,2024-11-04,PA003,London,Perth,E,210.0
3775,Yes,0,Dairy Free,2024-04-29,PA012,Tokyo,Perth,FC,3490.0
3776,Yes,2,Vegetarian,2024-09-26,PA001,London,New York,E,207.0
3777,Yes,1,Nut Free,2024-01-06,PA004,Perth,London,E,236.0

### 3. Create a month Column on which to join

In [44]:
sales_data['Date'] = pd.to_datetime(sales_data['Date'])

In [45]:
sales_data['Month'] = sales_data['Date'].dt.month

### 4. Total sales by class and month

In [55]:
sales_by_class_and_month = sales_data.groupby(['Month', 'Class'])['Price'].sum().reset_index()

In [74]:
sales_vs_target = pd.merge(sales_by_class_and_month, target_data, on=['Month', 'Class'])
sales_vs_target.columns = ['Month', 'Class', 'Sales', 'Target']

In [75]:
sales_vs_target['Difference to Target'] = sales_vs_target['Sales'] - sales_vs_target['Target']

In [76]:
sales_vs_target

    Month Class     Sales  Target  Difference to Target
0       1    BC   67297.5   85000              -17702.5
1       1     E   36081.0   31000                5081.0
2       1    FC  193960.0  120000               73960.0
3       1    PE   48555.6   40000                8555.6
4       2    BC   69222.5   86000              -16777.5
5       2     E   30968.0   31500                -532.0
6       2    FC  145665.0  130000               15665.0
7       2    PE   46335.6   40500                5835.6
8       3    BC   84357.5   87000               -2642.5
9       3     E   31829.0   32000                -171.0
10      3    FC  152315.0  140000               12315.0
11      3    PE   47875.2   41000                6875.2
12      4    BC   81522.5   88000               -6477.5
13      4     E   31333.0   34000               -2667.0
14      4    FC  224415.0  160000               64415.0
15      4    PE   38233.2   42500               -4266.8
16      5    BC   85065.0   89000               -3935.0
17      5     E   42898.0   34500                8398.0
18      5    FC  171610.0  170000                1610.0
19      5    PE   43833.6   43000                 833.6
20      6    BC   85735.0   90000               -4265.0
21      6     E   31440.0   35000               -3560.0
22      6    FC  149725.0  180000              -30275.0
23      6    PE   46538.4   43500                3038.4
24      7    BC   97490.0   92000                5490.0
25      7     E   38941.0   37000                1941.0
26      7    FC  172425.0  190000              -17575.0
27      7    PE   40258.8   46000               -5741.2
28      8    BC  106852.5   93000               13852.5
29      8     E   32820.0   37500               -4680.0
30      8    FC  209625.0  200000                9625.0
31      8    PE   41468.4   46500               -5031.6
32      9    BC   87590.0   95000               -7410.0
33      9     E   27724.0   38000              -10276.0
34      9    FC  200960.0  210000               -9040.0
35      9    PE   42054.0   47000               -4946.0
36     10    BC   94135.0   98000               -3865.0
37     10     E   32500.0   39000               -6500.0
38     10    FC  186185.0  220000              -33815.0
39     10    PE   43689.6   48000               -4310.4
40     11    BC   85970.0   99000              -13030.0
41     11     E   34023.0   39500               -5477.0
42     11    FC  154595.0  230000              -75405.0
43     11    PE   39372.0   48500               -9128.0
44     12    BC  100485.0  100000                 485.0
45     12     E   43588.0   40000                3588.0
46     12    FC  188015.0  240000              -51985.0
47     12    PE   45348.0   49000               -3652.0

## Save Results

In [77]:
sales_vs_target.to_csv('D:01_Projekt_Portfolio/data_prepping_challenges/sales_vs_target.csv')